#! /bin/bash
if [ $# -lt 1  ]
then
	echo Duong dan khong hop le
	exit 1
fi
path=$1
direct=${path##*/}
root=${path%%$direct}
echo $root $direct
if ! test -d $path
then

	echo Duong dan khong hop le
	exit 2
fi
echo -n Quyen cua nguoi dung voi thu muc la: " " 
echo  $( ls -l $root | grep $direct | cut -d" " -f1)

exit 0  
