#!/bin/bash
if [ $# -lt 1 ] 
then
	echo Khong co tham so dau vao
	exit 1
fi

n=$1
giaithua=1
i=1

while [ $i -lt $n -o $i -eq $n ]
do
	giaithua=$(( $giaithua * i ))
	i=$(( $i + 1 ))
done 

echo Giai thua cua $n la : $giaithua

exit 0
