#!/bin/bash
if [ $# -lt 1 -o $1 -lt 1 ]
then
	echo Tham so khong hop le
	exit 1
fi

for (( i=1; i<=$1; i++ ))
do
	for (( j=1; j<=$1; j++ )) 
	do
		if [ $j -lt $i ]
		then
			echo -n  " "
		else 
			echo -n "*"
		fi	
	done
	echo

done 
